comment:
  layout: header, changes, diff
coverage:
  notify:
    gitter:
      default:
        branches:
        - master
        threshold: 0
        url: https://webhooks.gitter.im/e/c88429a5ebc57dd5d52c
  status:
    patch: false